# Exercise


In [1]:
import torch
import numpy as np

## Given a Python list and a NumPy array, convert both to PyTorch tensors. 

In [2]:
arr = [1,2,3,4,5,6,7]
np_arr = np.array(arr)
torch_tensor = torch.from_numpy(np_arr)

## Create Tensors of Zeros and Ones

In [3]:
# Create a tensor with 20 elements, all set to 0.
zero_tensor = torch.zeros(20)

# Create a tensor with 25 elements, all set to 1
one_tensor = torch.ones(25)
zero_tensor, one_tensor

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]))

## Create a Random Tensor with Specific Shape and Type



In [4]:
# Create a random tensor with shape (5, 5) and data type float16.
random_tensor = torch.rand(size=(5, 5), dtype=torch.float16)
random_tensor

tensor([[0.9277, 0.3579, 0.4072, 0.1045, 0.7769],
        [0.0439, 0.3794, 0.9082, 0.8164, 0.7070],
        [0.9536, 0.3833, 0.7466, 0.7959, 0.5986],
        [0.5610, 0.6079, 0.0361, 0.6582, 0.0479],
        [0.2583, 0.4800, 0.0073, 0.2510, 0.0586]], dtype=torch.float16)

## Create a Tensor with a Range and Reshape

In [5]:
# Create a tensor with values from 1 to 40 (inclusive).
range_tensor = torch.arange(1, 41)

# Reshape this tensor to have shape (8, 5).
range_tensor.reshape(8, 5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]])

## Create a Tensor with Normal Distribution

In [6]:
# Create a tensor with the same shape as the previous tensor (8, 5), but fill it with values from a normal distribution.
# do not provide shape 
normal_tensor = torch.normal(0, 1, size=(8, 5))

## Create Identical Random Tensors Using a Seed

In [7]:
# Create two tensors, each with 10 random elements, but ensure both tensors are identical by setting the random seed before creation.
torch.manual_seed(42)
first_random_tensor = torch.rand(10)
torch.manual_seed(42)
second_random_tensor = torch.rand(10)
torch.equal(first_random_tensor, second_random_tensor)

True

## Tensor Indexing and Slicing

In [ ]:
# Create a tensor using arange from 1 to 40, reshape it to shape (5, 4, 2), and name it x.
x = torch.arange(1, 41).reshape(5, 4, 2)
# Get all elements with index 0 from axis 2 of x.
print(x[: , :, 0])
# Get all elements with index 2 to 4 from axis 0 of x.
print(x[0][2:4])
# Get all elements with index 2 to the end from axis 1 and index 1 to the end from axis 2 of x.
print(x[1][2:])
print(x[2][1:])
# Reshape x to have 8 rows (axis 0) and as many columns as needed (do not specify the number of columns directly).
x.reshape(8, -1)

tensor([[ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23],
        [25, 27, 29, 31],
        [33, 35, 37, 39]])
tensor([[5, 6],
        [7, 8]])
tensor([[13, 14],
        [15, 16]])
tensor([[19, 20],
        [21, 22],
        [23, 24]])
tensor([[[ 6],
         [ 8]],

        [[14],
         [16]],

        [[22],
         [24]],

        [[30],
         [32]],

        [[38],
         [40]]])


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]])

## Tensor Operations: Multiplication and Summation

In [9]:
# Create a tensor y with elements from 1 to 12 and shape (4, 3).
y = torch.arange(1, 13).reshape(4, 3)
# Multiply each item in y by 2, then sum over axis 0.
torch.sum(y * 2 , axis=0)

tensor([44, 52, 60])

## Dot Product of Two Tensors

In [10]:
# Create a tensor with elements [1,2,3] Compute the dot product with another tensor [4,5,6]
torch.dot(torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6]))

tensor(32)

## Matrix Multiplication with torch.matmul

In [11]:
torch.arange(101, 113)

tensor([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])

In [12]:
# Create tensor A with shape (2, 2, 3) and elements of your choice.
A = torch.arange(101, 113).reshape(2, 2, 3).type(torch.float32)
# Create tensor B with shape (3, 4) and elements of your choice.
B = torch.linspace(-1, 1, 12).reshape(3, 4).type(torch.float32)
# Multiply A and B using torch.matmul and display the result.
torch.matmul(A, B)

tensor([[[-82.0000, -26.3636,  29.2727,  84.9091],
         [-84.4546, -27.1818,  30.0909,  87.3636]],

        [[-86.9091, -28.0000,  30.9091,  89.8182],
         [-89.3636, -28.8182,  31.7273,  92.2727]]])

In [21]:
torch.manual_seed(4026)
torch.randint(1, 1000, (1, 2)), torch.randint(1, 1000 , (1, 2))

(tensor([[638, 414]]), tensor([[563, 287]]))

In [23]:
torch.randn(100)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
# 1


cpu
